### ISSUE TITLE
Getting exception while creating any application which is already exists on iTunesconnect

### ISSUE THREAD

**Issue by chintan1891** [fastlane/produce#43]
Hi,
I am trying to run "produce" tool with a Bundle ID which is already there on iTunesconnect.
This tool is throwing an exception instead on giving proper error message.

Below is the exception detail : 

```
[11:51:03]: ["/Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/lib/produce/itunes_connect.rb:87:in `initial_create'", "/Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/lib/produce/itunes_connect.rb:39:in `create_new_app'", "/Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/lib/produce/itunes_connect.rb:27:in `run'", "/Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/lib/produce/manager.rb:8:in `start_producing'", "/Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/bin/produce:33:in `block (2 levels) in run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'", "/Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/bin/produce:46:in `run'", "/Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/bin/produce:52:in `<top (required)>'", "/usr/bin/produce:23:in `load'", "/usr/bin/produce:23:in `<main>'"]
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.7.6/lib/fastlane_core/itunes_connect/itunes_connect_helper.rb:76:in `wait_for_elements': Couldn't find element 'option[value='Bundle ID Goes here']' after waiting for quite some time (FastlaneCore::ItunesConnect::ItunesConnectGeneralError)
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/lib/produce/itunes_connect.rb:87:in `initial_create'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/lib/produce/itunes_connect.rb:39:in `create_new_app'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/lib/produce/itunes_connect.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/lib/produce/manager.rb:8:in `start_producing'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/bin/produce:33:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/bin/produce:46:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.3.0/bin/produce:52:in `<top (required)>'
    from /usr/bin/produce:23:in `load'
    from /usr/bin/produce:23:in `<main>'
```

**Comment by ericertl** [comment]
I experienced this one too. It'd be nice to show an error telling the appid is already created instead of this crash

**Comment by KrauseFx** [comment]
That shouldn't happen and has worked before. Apple seemed to have changed something on their API, I'll take a closer look at this :+1:

**Comment by wkoszek** [comment]
Hi guys. Same issue here. Also the error warning has some duplicated text

```
[11:49:57]: [DevCenter] App 'com.koszek.x.develop' already exists, nothing to do on the Dev Center
[11:49:59]: Creating new app 'x' on iTunes Connect
Error happened![11:50:08]: Variable Dump:
[11:50:08]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appmake"}
[11:50:08]: The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 6           |
| 4    | slack                               | 1           |
| 5    | produce                             | 14          |
+------+-------------------------------------+-------------+

[11:50:08]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used. (Spaceship::TunesClient::ITunesConnectError)
    from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.19.3/lib/spaceship/tunes/tunes_client.rb:281:in `create_application!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.19.3/lib/spaceship/tunes/application.rb:86:in `create!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/produce-1.1.1/lib/produce/itunes_connect.rb:25:in `create_new_app'
    from /usr/local/lib/ruby/gems/2.2.0/gems/produce-1.1.1/lib/produce/itunes_connect.rb:12:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/produce-1.1.1/lib/produce/manager.rb:8:in `start_producing'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/actions/produce.rb:19:in `block in run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/actions/produce.rb:17:in `chdir'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/actions/produce.rb:17:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:129:in `block in execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:128:in `chdir'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:128:in `execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/fast_file.rb:149:in `method_missing'
    from Fastfile:30:in `block (2 levels) in parsing_binding'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/lane.rb:36:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/lane.rb:36:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:52:in `block in execute'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:46:in `chdir'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/runner.rb:46:in `execute'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/bin/fastlane:38:in `block (2 levels) in run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/bin/fastlane:150:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.55.0/bin/fastlane:156:in `<top (required)>'
    from /usr/local/bin/fastlane:23:in `load'
    from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
@wkoszek that error is not related

> [11:50:08]: The App Name you entered has already been used. The App Name you entered has already been used. The App Name you entered has already been used.

The name of your app is already taken

**Comment by wkoszek** [comment]
@KrauseFx hm.. OK. Could we fallback gracefully somehow? I'm in the process of figuring out the flow for my app.

What would be cool: ability to run the whole flow for app creation/registration/uploading always. Something like: "create if not exists" in SQL.

**Comment by KrauseFx** [comment]
@wkoszek so how would that look like? If the name is already taken the only thing `produce` could do is to select a random name to bypass the iTunes Connect validation.
