### ISSUE TITLE
produce associate_group returns a 400 error

### ISSUE THREAD

**Issue by mashour** [fastlane/produce#75]
When trying to associate an app with an app group using the following command:

produce associate_group -u username@mac.com -a com.team.app group.com.team.app

I get the following error:

```
[13:28:14]: Successfully logged in
[13:28:19]: Validating groups before association
[13:28:24]: Finalising association with 1 groups
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse': 757: unexpected token at 'HTTP 400 Bad Request' (Faraday::ParsingError)
    from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
    from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
    from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
    from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/client.rb:228:in `block in send_request'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/client.rb:160:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/client.rb:160:in `with_retry'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/client.rb:227:in `send_request'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/client.rb:203:in `request'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/portal/portal_client.rb:126:in `associate_groups_with_app'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/portal/app.rb:127:in `associate_groups'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.2/lib/produce/group.rb:64:in `associate'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.2/bin/produce:116:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.2/bin/produce:122:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/produce-0.6.2/bin/produce:128:in `<top (required)>'
    from /usr/bin/produce:23:in `load'
    from /usr/bin/produce:23:in `<main>'
```

![image](https://cloud.githubusercontent.com/assets/3940780/9760609/d1b75e66-56f6-11e5-8c53-597484df770c.png)

**Comment by glancashire** [comment]
I get the exact same error
