### ISSUE TITLE
authentication.failed: Your session has expired. Please log in.

### ISSUE THREAD

**Issue by nmeyer** [fastlane/produce#82]
Hiya!

I'm getting the following error when trying to use produce:

```
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.12.2/lib/spaceship/client.rb:255:in `parse_response': {"responseId"=>"98c8f5a5-37ca-415b-ab97-ce0b22f4fd32", "resultCode"=>1100, "resultString"=>"authentication.failed", "userString"=>"Your session has expired.  Please log in.", "creationTimestamp"=>"2015-10-22T19:37:43Z", "protocolVersion"=>"QH65B2", "requestId"=>nil, "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/listTeams.action", "httpCode"=>200} (Spaceship::Client::UnexpectedResponse)
    from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.12.2/lib/spaceship/portal/portal_client.rb:58:in `teams'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.12.2/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.12.2/lib/spaceship/portal/portal_client.rb:74:in `select_team'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.12.2/lib/spaceship/portal/spaceship.rb:37:in `select_team'
    from /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.12.2/lib/spaceship/portal/spaceship.rb:81:in `select_team'
    from /usr/local/lib/ruby/gems/2.2.0/gems/produce-1.0.0/lib/produce/developer_center.rb:54:in `login'
    from /usr/local/lib/ruby/gems/2.2.0/gems/produce-1.0.0/lib/produce/developer_center.rb:7:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/produce-1.0.0/lib/produce/manager.rb:5:in `start_producing'
    from /usr/local/lib/ruby/gems/2.2.0/gems/produce-1.0.0/bin/produce:33:in `block (2 levels) in run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/produce-1.0.0/bin/produce:123:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/produce-1.0.0/bin/produce:129:in `<top (required)>'
    from /usr/local/bin/produce:23:in `load'
    from /usr/local/bin/produce:23:in `<main>'
```

I can login via spaceship just fine (uses keychain, doesn't ask for my password). But using the same Username with produce results in the session expired error.

Any ideas? Thanks!

**Comment by truth3** [comment]
@nmeyer It is happening on all developer portal related requests, but as long as you have the assets local you can still build and upload. Hope that helps

https://github.com/KrauseFx/sigh/issues/188

**Comment by nmeyer** [comment]
ahhh thanks @truth3. Oh Apple. Fun week for all of us...
